<?php
define("C_HOST","localhost");
define("C_USER","root");
define("C_PASS","");
//define("C_DB","espredu_pap2019");
define("C_DB","biblioteca");
define("MENUON",true);
define("MENUOFF",false);
define("LIVROS",1);
define("AUTORES",2);
define("UTILIZADORES",3);
define("AUTORES2",4);
define("HOME",0);
define("AUTORES3",5);
?>